### ISSUE TITLE
Add prometheus tracking

### ISSUE THREAD

**Issue by mrarticuno** [gmlyra/jaas#12]
### Feature
Add prometheus metrics to project

- [ ] Tracking requests per second
- [ ] Track amount of data transferred
- [ ] Track amount of data stored
- [ ] Track errors on all apps
